### ISSUE TITLE
Build issue while running the App with SPM package

### ISSUE THREAD

**Issue by Milap-Kundalia-Einfochips** [wendyliga/resource-spm#4]
Hi,

I have requirement of loading the asset from SPM package in to my SwiftUI project. I came across your Medium blog and found a github demo link in SPM package. When I tried to add your SPM package into my app for testing purpose. Its giving me couple of errors in main.swift. Screen shot attached

1) Missing argument for parameter 'compatibleWith' in call
2) Cannot find 'imageInXCassets' in scope

<img width="969" alt="Screenshot 2023-10-10 at 12 23 31 PM" src="https://github.com/wendyliga/resource-spm/assets/134631808/df29f3ec-2a67-4b4f-847f-7b419696e38b">

Tested in Xcode 14.3

Can you please look into this.

Thanks

**Comment by wendyliga** [comment]
fixed on https://github.com/wendyliga/resource-spm/commit/b315944b783a0da50449c1f228a49e4e019debec
